set_property PACKAGE_PIN D19 [get_ports button_view]
set_property PACKAGE_PIN D20 [get_ports button_select]
set_property PACKAGE_PIN L19 [get_ports button_pay]
set_property PACKAGE_PIN L20 [get_ports button_admin]
set_property PACKAGE_PIN H16 [get_ports clk]
set_property PACKAGE_PIN R14 [get_ports led]
